* [tslint] Added hook pre-commit with TSlint

diff --git a/git-hooks/pre-commit b/git-hooks/pre-commit
--- a/git-hooks/pre-commit
+++ b/git-hooks/pre-commit
@@ -1,9 +1,4 @@
 #!/bin/sh
-pass=true
-NC='\033[0m'
-RED='\033[1;31m'
-GREEN='\033[0;32m'
-
 echo "Running Linters:"
 
 # Run tslint and get the output and return code
@@ -12,9 +7,10 @@ ret_code=$?
 
 # If it didn't pass, announce it failed and print the output
 if [ $ret_code != 0 ]; then
-	printf "\n${RED}tslint failed:${NC}"
+	printf "TSlint FAILED: Commit contains files with TSlint errors !!!"
 	echo "$tslint\n"
-	pass=false
+	exit 1
 else
-	printf "${GREEN}tslint passed.${NC}\n"
+	printf "TSlint SUCCESS: Commit allowed."
+	exit 0
 fi
